import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./App.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { Toaster } from '@/components/ui/sonner';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col min-h-screen">
          <Header />
          <main className="grow">{children}</main>
          {/* Global toaster for notifications */}
          <Toaster
            position="top-right"
            expand={true}
            richColors
            toastOptions={{
              classNames: {
                toast:
                  'group flex w-full max-w-sm items-center gap-3 overflow-hidden rounded-xl border border-gray-200 bg-white px-4 py-3 shadow-lg transition-all duration-300 hover:scale-[1.02] dark:bg-neutral-900 dark:border-neutral-800',
                title:
                  'text-sm font-semibold text-gray-900 dark:text-gray-100 group-hover:text-primary transition-colors',
                description:
                  'text-xs text-gray-600 dark:text-gray-400 group-hover:text-gray-800 dark:group-hover:text-gray-200 transition-colors',
                actionButton:
                  'rounded-md bg-primary px-2 py-1 text-xs font-medium text-primary-foreground shadow-sm transition-all hover:bg-primary/90',
                cancelButton:
                  'rounded-md border border-gray-300 px-2 py-1 text-xs font-medium text-gray-700 transition-all hover:bg-gray-100 dark:border-neutral-700 dark:text-gray-300 dark:hover:bg-neutral-800',
              },
            }}
          />

          <Footer />
        </div>
      </body>
    </html>
  );
}
